### ISSUE TITLE
Move Metabase AWS billing to an organization

### ISSUE THREAD

**Issue by xdg** [cpan-testers/cpantesters-project#15]
Currently, I pay the Metabase bills and submit to EPO for reimbursement.

If something happens to me (or my credit card), Metabase could go down.

Even as we consider future alternatives to Metabase, we should move responsibility for resource payments to an organization that can sustain it over time.

**Comment by preaction** [comment]
Will EPO do that? Is there a way in AWS to add multiple accounts as responsible for a group of machines? If so, I can add mine and we'll have some protection.

Otherwise, I got $work to give us a couple machines in a rack which should be provisioned soon, so we at least have some hardware for that future alternative.

**Comment by preaction** [comment]
The Metabase AWS instances have been shut down, and the account closed.
